services:
  database_postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spark-db
      POSTGRES_USER: spark-user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spark-user -d spark-db"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - spark-network

  mailpit:
    image: axllent/mailpit:v1.29
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - spark-network

volumes:
  postgres_data:

networks:
  spark-network:
    driver: bridge
