<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.flare.spark</groupId>
    <artifactId>parent</artifactId>
    <version>1</version>
    <packaging>pom</packaging>

    <modules>
        <module>backend</module>
        <module>frontend</module>
    </modules>

    <properties>
        <openapi-generator-maven-plugin.version>7.22.0</openapi-generator-maven-plugin.version>
        <swagger-annotations.version>2.2.25</swagger-annotations.version>
        <jakarta.version>3.1.1</jakarta.version>
        <frontend-maven-plugin.version>1.15.1</frontend-maven-plugin.version>
        <node.version>v26.1.0</node.version>
        <npm.version>11.14.1</npm.version>
    </properties>
</project>