openapi: 3.0.3
info:
  title: Spark Bundle API
  version: 0.0.1

servers:
  - url: http://localhost:8080

paths:
  /api/v1/bundles:
    get:
      tags:
        - Bundles
      summary: Get a list of bundles
      operationId: getBundles
      responses:
        200:
          description: List of bundles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bundle'

  /api/v1/bundles/create:
    post:
      tags:
        - Bundles
      summary: Create a new bundle
      operationId: createBundle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBundleRequest'
      responses:
        200:
          description: Returns the generated Bundle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bundle'

components:
  schemas:
    Bundle:
      type: object
      required:
        - id
        - name
        - slug
        - readme
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        readme:
          type: string

    CreateBundleRequest:
      type: object
      required:
        - name
        - slug
        - readme
      properties:
        name:
          type: string
        slug:
          type: string
        readme:
          type: string