openapi: 3.0.0
info:
  title: Spark Bundle API
  version: 0.0.1

paths:
  /api/v1/bundles:
    get:
      summary: Get all bundles
      responses:
        '200':
          description: List of bundles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bundle'

components:
  schemas:
    Bundle:
      type: object
      required:
        - id
        - name
        - slug
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string