openapi: 3.0.3
info:
  title: Spark Bundle API
  version: 0.0.1

servers:
  - url: http://localhost:8080

paths:
  /api/v1/bundles:
    get:
      tags:
        - Bundles
      summary: Get a list of bundles
      operationId: getBundles
      parameters:
        - in: path
          name: page
          required: false
          schema:
            type: integer
            description: current page number
      responses:
        200:
          description: List of bundles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bundle'
    post:
      tags:
        - Bundles
      summary: Create a new bundle
      operationId: createBundle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBundle'
      responses:
        200:
          description: Returns the generated Bundle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bundle'

  /api/v1/bundles/{id}/upload:
    post:
      tags:
        - Bundles
      summary: Will be to upload files to the backend
      operationId: uploadBundleFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              title: UploadBundleFileRequest
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Uploaded succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResult'

components:
  schemas:
    Bundle:
      type: object
      required:
        - id
        - name
        - slug
        - description
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        description:
          type: string

    SlicedPagination:
      type: object
      required:
        - pageNumber
        - pageSize
        - isFirst
        - isLast
        - isEmpty
      properties:
        pageNumber:
          type: integer
        pageSize:
          type: integer
        isFirst:
          type: boolean
        isLast:
          type: boolean
        isEmpty:
          type: boolean

    PaginatedBundles:
      type: object
      required:
        - content
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Bundle'
      allOf:
      - $ref: '#/components/schemas/SlicedPagination'

    CreateBundle:
      type: object
      required:
        - name
        - description
        - status
      properties:
        name:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [PUBLIC, PRIVATE]

    UploadResult:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid