/**
 * Spark Bundle API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Bundle { 
    id: string;
    name: string;
    slug: string;
}

