spark-variables:
  cors:
    allowed-origin: http://localhost:5173

spring:
  docker:
    compose:
      lifecycle-management: none  # this is external on prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: WARN
    com.flare.spark: INFO
