spark-variables:
  cors:
    allowed-origin: http://localhost:5173
  csrf:
    enabled: false
  seed-database: true

spring:
  docker:
    compose:
      file: docker-compose.yaml
      lifecycle-management: start_only

  mail:
    host: localhost
    port: 1025

  datasource:
    url: jdbc:postgresql://localhost:5432/spark-db
    username: spark-user
    password: password

  flyway:
    enabled: true
    validate-on-migrate: true
    validate-migration-naming: true

  jpa:
    show-sql: on

logging:
  level:
    root: INFO
    com.flare.spark: DEBUG