spark-variables:
  cors:
    allowed-origin: http://localhost:5173

spring:
  docker:
    compose:
      lifecycle-management: none  # this is external on prod
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}

logging:
  level:
    root: WARN
    com.flare.spark: INFO
