spark-variables:
  cors:
    allowed-origin: http://localhost:5173
  seed-database: true

spring:
  docker:
    compose:
      file: docker-compose.yaml
      lifecycle-management: start_only

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    validate-on-migrate: true
    validate-migration-naming: true

logging:
  level:
    root: INFO
    com.flare.spark: DEBUG
